version: '3'

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./avatars:/usr/src/app/avatars
      - ./data:/usr/src/app/data
    environment:
      - FLASHPAPER_USING_PROXY=TRUE
      - FLASHPAPER_WEBHOOKS_ENABLED=TRUE
    ports:
      - 5000:5000
